### ISSUE TITLE
Error in Visual Studio Code caused by lualinter

### ISSUE THREAD

**Issue by irimiab** [dcr30/vscode-lualinter#5]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|lualinter|dcr30|1.0.3|

I keep getting this error in the Visual Studio Code's developer console:

```
Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at C:\Users\bogdan\.vscode\extensions\dcr30.lualinter-1.0.3\out\src\extension.js:93:93
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:1748)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:5235)
    at t.$acceptActiveEditorAndVisibleEditors (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:13:8151)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:2729)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:8:15667)
    at d (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:8:16344)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by nbredikhin** [comment]
Thank you for reporting the error, I'll fix it as soon as I can.
